spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testertonieprogramista
    password: coolpassword
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect